window.esdocSearchIndex = [
  [
    "./lib/gulp-graph.js~gulpgraph",
    "class/lib/gulp-graph.js~GulpGraph.html",
    '<span>GulpGraph</span> <span class="search-result-import-path">./lib/gulp-graph.js</span>',
    "class"
  ],
  [
    "./lib/gulp-nodes.js~gulpnode",
    "variable/index.html#static-variable-GulpNode",
    '<span>GulpNode</span> <span class="search-result-import-path">./lib/gulp-nodes.js</span>',
    "variable"
  ],
  [
    "./lib/interface.js~gulpnode",
    "class/lib/interface.js~GulpNode.html",
    '<span>GulpNode</span> <span class="search-result-import-path">./lib/interface.js</span>',
    "class"
  ],
  [
    "./lib/gulp-graph.js~jointgraph",
    "variable/index.html#static-variable-JointGraph",
    '<span>JointGraph</span> <span class="search-result-import-path">./lib/gulp-graph.js</span>',
    "variable"
  ],
  [
    "./lib/interface.js~jointgraph",
    "class/lib/interface.js~JointGraph.html",
    '<span>JointGraph</span> <span class="search-result-import-path">./lib/interface.js</span>',
    "class"
  ],
  [
    "./lib/gulp-nodes.js~packagenode",
    "class/lib/gulp-nodes.js~PackageNode.html",
    '<span>PackageNode</span> <span class="search-result-import-path">./lib/gulp-nodes.js</span>',
    "class"
  ],
  [
    "./lib/gulp-nodes.js~tasknode",
    "class/lib/gulp-nodes.js~TaskNode.html",
    '<span>TaskNode</span> <span class="search-result-import-path">./lib/gulp-nodes.js</span>',
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/gulp-graph.js",
    "file/lib/gulp-graph.js.html",
    "lib/gulp-graph.js",
    "file"
  ],
  [
    "lib/gulp-graph.js~gulpgraph#assemblegraph",
    "class/lib/gulp-graph.js~GulpGraph.html#instance-method-assemblegraph",
    "lib/gulp-graph.js~GulpGraph#assemblegraph",
    "method"
  ],
  [
    "lib/gulp-graph.js~gulpgraph#constructor",
    "class/lib/gulp-graph.js~GulpGraph.html#instance-constructor-constructor",
    "lib/gulp-graph.js~GulpGraph#constructor",
    "method"
  ],
  [
    "lib/gulp-graph.js~gulpgraph#definesubtask",
    "class/lib/gulp-graph.js~GulpGraph.html#instance-method-defineSubTask",
    "lib/gulp-graph.js~GulpGraph#defineSubTask",
    "method"
  ],
  [
    "lib/gulp-graph.js~gulpgraph#definetask",
    "class/lib/gulp-graph.js~GulpGraph.html#instance-method-defineTask",
    "lib/gulp-graph.js~GulpGraph#defineTask",
    "method"
  ],
  [
    "lib/gulp-nodes.js",
    "file/lib/gulp-nodes.js.html",
    "lib/gulp-nodes.js",
    "file"
  ],
  [
    "lib/gulp-nodes.js~packagenode#identifier",
    "class/lib/gulp-nodes.js~PackageNode.html#instance-member-IDENTIFIER",
    "lib/gulp-nodes.js~PackageNode#IDENTIFIER",
    "member"
  ],
  [
    "lib/gulp-nodes.js~packagenode#type",
    "class/lib/gulp-nodes.js~PackageNode.html#instance-member-TYPE",
    "lib/gulp-nodes.js~PackageNode#TYPE",
    "member"
  ],
  [
    "lib/gulp-nodes.js~packagenode#constructor",
    "class/lib/gulp-nodes.js~PackageNode.html#instance-constructor-constructor",
    "lib/gulp-nodes.js~PackageNode#constructor",
    "method"
  ],
  [
    "lib/gulp-nodes.js~packagenode#identifier",
    "class/lib/gulp-nodes.js~PackageNode.html#instance-get-identifier",
    "lib/gulp-nodes.js~PackageNode#identifier",
    "member"
  ],
  [
    "lib/gulp-nodes.js~tasknode#task_dependencies",
    "class/lib/gulp-nodes.js~TaskNode.html#instance-member-TASK_DEPENDENCIES",
    "lib/gulp-nodes.js~TaskNode#TASK_DEPENDENCIES",
    "member"
  ],
  [
    "lib/gulp-nodes.js~tasknode#type",
    "class/lib/gulp-nodes.js~TaskNode.html#instance-member-TYPE",
    "lib/gulp-nodes.js~TaskNode#TYPE",
    "member"
  ],
  [
    "lib/gulp-nodes.js~tasknode#constructor",
    "class/lib/gulp-nodes.js~TaskNode.html#instance-constructor-constructor",
    "lib/gulp-nodes.js~TaskNode#constructor",
    "method"
  ],
  [
    "lib/gulp-nodes.js~tasknode#linkdependencies",
    "class/lib/gulp-nodes.js~TaskNode.html#instance-method-linkDependencies",
    "lib/gulp-nodes.js~TaskNode#linkDependencies",
    "method"
  ],
  [
    "lib/interface.js",
    "file/lib/interface.js.html",
    "lib/interface.js",
    "file"
  ],
  [
    "lib/interface.js~gulpnode#name",
    "class/lib/interface.js~GulpNode.html#instance-member-NAME",
    "lib/interface.js~GulpNode#NAME",
    "member"
  ],
  [
    "lib/interface.js~gulpnode#type",
    "class/lib/interface.js~GulpNode.html#instance-member-TYPE",
    "lib/interface.js~GulpNode#TYPE",
    "member"
  ],
  [
    "lib/interface.js~gulpnode#addself",
    "class/lib/interface.js~GulpNode.html#instance-method-addSelf",
    "lib/interface.js~GulpNode#addSelf",
    "method"
  ],
  [
    "lib/interface.js~gulpnode#constructor",
    "class/lib/interface.js~GulpNode.html#instance-constructor-constructor",
    "lib/interface.js~GulpNode#constructor",
    "method"
  ],
  [
    "lib/interface.js~gulpnode#label",
    "class/lib/interface.js~GulpNode.html#instance-get-label",
    "lib/interface.js~GulpNode#label",
    "member"
  ],
  [
    "lib/interface.js~gulpnode#name",
    "class/lib/interface.js~GulpNode.html#instance-get-name",
    "lib/interface.js~GulpNode#name",
    "member"
  ],
  [
    "lib/interface.js~gulpnode#type",
    "class/lib/interface.js~GulpNode.html#instance-get-type",
    "lib/interface.js~GulpNode#type",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#config",
    "class/lib/interface.js~JointGraph.html#instance-member-CONFIG",
    "lib/interface.js~JointGraph#CONFIG",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#dependencies",
    "class/lib/interface.js~JointGraph.html#instance-member-DEPENDENCIES",
    "lib/interface.js~JointGraph#DEPENDENCIES",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#graph",
    "class/lib/interface.js~JointGraph.html#instance-member-GRAPH",
    "lib/interface.js~JointGraph#GRAPH",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#gulp_js",
    "class/lib/interface.js~JointGraph.html#instance-member-GULP_JS",
    "lib/interface.js~JointGraph#GULP_JS",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#config",
    "class/lib/interface.js~JointGraph.html#instance-get-config",
    "lib/interface.js~JointGraph#config",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#config",
    "class/lib/interface.js~JointGraph.html#instance-set-config",
    "lib/interface.js~JointGraph#config",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#constructor",
    "class/lib/interface.js~JointGraph.html#instance-constructor-constructor",
    "lib/interface.js~JointGraph#constructor",
    "method"
  ],
  [
    "lib/interface.js~jointgraph#dependencies",
    "class/lib/interface.js~JointGraph.html#instance-get-dependencies",
    "lib/interface.js~JointGraph#dependencies",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#dependencies",
    "class/lib/interface.js~JointGraph.html#instance-set-dependencies",
    "lib/interface.js~JointGraph#dependencies",
    "member"
  ],
  [
    "lib/interface.js~jointgraph#todot",
    "class/lib/interface.js~JointGraph.html#instance-method-toDOT",
    "lib/interface.js~JointGraph#toDOT",
    "method"
  ],
  [
    "lib/interface.js~jointgraph#tojson",
    "class/lib/interface.js~JointGraph.html#instance-method-toJSON",
    "lib/interface.js~JointGraph#toJSON",
    "method"
  ]
];
